#!/bin/bash -x
#
# runsv(8) script that starts Jetty.
#
# This can also be run manually (e.g. on developer's system) to run Jetty in a
# terminal. To do that, you'll want to set $JETTY_HOME and $JAVA_HOME.
# Everything else should be taken care of automatically.

# Redirect stdout to stderr so that our log script catches it
exec 2>&1

# Read some default settings from the environment
[[ -f $(dirname $0)/env ]] && . $(dirname $0)/env

export JETTY_HOME=${JETTY_HOME:-/opt/jetty}
export JAVA_HOME=${JAVA_HOME:-/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.25.x86_64}
export CRIMEDB_HOME=${CRIMEDB_HOME:-$(readlink -f $(dirname $(readlink -f $0))/../..)}
export SOLR_HOME=${SOLR_HOME:-$CRIMEDB_HOME/solr}

cd $CRIMEDB_HOME/jetty

exec $JAVA_HOME/bin/java \
    -Djetty.home=$JETTY_HOME \
    -Dsolr.solr.home=$SOLR_HOME \
    -jar $JETTY_HOME/start.jar \
    lib=$CRIMEDB_HOME/jetty/ext
